In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sharankumare/mcq-test/test.csv
/kaggle/input/datasets/sharankumare/mcq-train/train.csv

In [2]:
!pip install -q transformers datasets sentencepiece

In [3]:
import torch
import pandas as pd

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)

In [4]:
import os

for dirname, _, filenames in os.walk("/kaggle/input"):
    for filename in filenames:
        if filename == "train.csv":
            print(os.path.join(dirname, filename))

/kaggle/input/datasets/sharankumare/mcq-train/train.csv

In [5]:
train = pd.read_csv("/kaggle/input/datasets/sharankumare/mcq-train/train.csv")

print(train.shape)
train.head()

(2000, 8)

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

In [6]:
label_map = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

train["label"] = train["answer"].map(label_map)

train[["answer", "label"]].head()

  answer  label
0      B      1
1      A      0
2      C      2
3      B      1
4      A      0

In [7]:
device = 'cuda'if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [8]:
deberta_checkpoint = "microsoft/deberta-v3-small"

deberta_tokenizer = AutoTokenizer.from_pretrained(
    deberta_checkpoint
)

deberta_model = AutoModelForSequenceClassification.from_pretrained(
    deberta_checkpoint,
    num_labels=5
)

deberta_model = deberta_model.to(device)

print("DeBERTa loaded")

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/286M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/286M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-small
Key                                     | Status     |
----------------------------------------+------------+-
mask_predictions.dense.bias             | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
classifier.weight                       | MISSING    |
pooler.dense.bias                       | MISSING    |
classifier.bias                         | MISSING    |
pooler.dense.weight                     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

DeBERTa loaded

In [9]:
roberta_checkpoint = "roberta-base"

roberta_tokenizer = AutoTokenizer.from_pretrained(
    roberta_checkpoint
)

roberta_model = AutoModelForSequenceClassification.from_pretrained(
    roberta_checkpoint,
    num_labels=5
)

roberta_model = roberta_model.to(device)

print("RoBERTa loaded")

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

RoBERTa loaded

In [10]:
id_to_option = {
    0: "A",
    1: "B",
    2: "C",
    3: "D",
    4: "E"
}

print(id_to_option)

{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'}

In [11]:
import torch

prompt_25 = str(train.loc[25, "prompt"])

deberta_inputs = deberta_tokenizer(
    prompt_25,
    return_tensors="pt",
    truncation=True,
    padding=True
)

deberta_inputs = {
    key: value.to(device)
    for key, value in deberta_inputs.items()
}

deberta_model.eval()

with torch.no_grad():
    deberta_outputs = deberta_model(**deberta_inputs)

deberta_logits = deberta_outputs.logits

deberta_probs = torch.softmax(
    deberta_logits,
    dim=-1
)

print("Logits:")
print(deberta_logits)

print("\nProbabilities:")
print(deberta_probs)

Logits:
tensor([[-0.4126,  0.3135,  0.0891,  0.0803, -0.2467]], device='cuda:0',
       dtype=torch.float16)

Probabilities:
tensor([[0.1327, 0.2742, 0.2191, 0.2173, 0.1566]], device='cuda:0',
       dtype=torch.float16)

In [12]:
options = ["A", "B", "C", "D", "E"]

highest_label = torch.argmax(
    deberta_probs,
    dim=-1
).item()

highest_probability = deberta_probs[0, highest_label].item()

highest_option = options[highest_label]

print("Option:", highest_option)
print("Probability:", highest_probability)

print(
    f"Answer: {highest_option}, {highest_probability:.4f}"
)

Option: B
Probability: 0.274169921875
Answer: B, 0.2742

In [13]:
# RoBERTa inference on row index 25

prompt_25 = str(train.loc[25, "prompt"])

roberta_inputs = roberta_tokenizer(
    prompt_25,
    return_tensors="pt",
    truncation=True,
    padding=True
)

roberta_inputs = {
    key: value.to(device)
    for key, value in roberta_inputs.items()
}

roberta_model.eval()

with torch.no_grad():
    roberta_outputs = roberta_model(**roberta_inputs)

roberta_probs = torch.softmax(
    roberta_outputs.logits,
    dim=-1
)

print("RoBERTa probabilities:")
print(roberta_probs)

RoBERTa probabilities:
tensor([[0.1763, 0.2296, 0.1809, 0.2016, 0.2115]], device='cuda:0')

In [14]:
average_probs = (
    deberta_probs + roberta_probs
) / 2

options = ["A", "B", "C", "D", "E"]

highest_label = torch.argmax(
    average_probs,
    dim=-1
).item()

highest_option = options[highest_label]

print("DeBERTa probabilities:", deberta_probs)
print("RoBERTa probabilities:", roberta_probs)
print("Average probabilities:", average_probs)

print("Answer:", highest_option)

DeBERTa probabilities: tensor([[0.1327, 0.2742, 0.2191, 0.2173, 0.1566]], device='cuda:0',
       dtype=torch.float16)
RoBERTa probabilities: tensor([[0.1763, 0.2296, 0.1809, 0.2016, 0.2115]], device='cuda:0')
Average probabilities: tensor([[0.1545, 0.2519, 0.2000, 0.2094, 0.1841]], device='cuda:0')
Answer: B

In [15]:
weighted_probs = (
    0.70 * deberta_probs
    + 0.30 * roberta_probs
)

options = ["A", "B", "C", "D", "E"]

highest_label = torch.argmax(
    weighted_probs,
    dim=-1
).item()

highest_option = options[highest_label]

print("DeBERTa probabilities:", deberta_probs)
print("RoBERTa probabilities:", roberta_probs)
print("Weighted probabilities:", weighted_probs)

print("Answer:", highest_option)

DeBERTa probabilities: tensor([[0.1327, 0.2742, 0.2191, 0.2173, 0.1566]], device='cuda:0',
       dtype=torch.float16)
RoBERTa probabilities: tensor([[0.1763, 0.2296, 0.1809, 0.2016, 0.2115]], device='cuda:0')
Weighted probabilities: tensor([[0.1458, 0.2608, 0.2076, 0.2126, 0.1731]], device='cuda:0')
Answer: B

In [16]:
options = ["A", "B", "C", "D", "E"]

top3_indices = torch.argsort(
    weighted_probs,
    dim=-1,
    descending=True
)[0, :3]

top3_options = [
    options[i.item()]
    for i in top3_indices
]

top3_prediction = " ".join(top3_options)

print("Top-3 indices:", top3_indices)
print("Top-3 options:", top3_options)
print("Kaggle prediction:", top3_prediction)

Top-3 indices: tensor([1, 3, 2], device='cuda:0')
Top-3 options: ['B', 'D', 'C']
Kaggle prediction: B D C

In [17]:
test = pd.read_csv(
    "/kaggle/input/datasets/sharankumare/mcq-test/test.csv"
)

print("Test shape:", test.shape)
test.head()

Test shape: (500, 7)

,id,prompt,A,B,C,D,E
0,1,Pick the best possible answer: What is the rel...,"For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p..."
1,2,"What is the estimated redshift of CEERS-93316,...","Approximately z = 6.0, corresponding to 1 bill...","Approximately z = 16.7, corresponding to 235.8...","Approximately z = 3.0, corresponding to 5 bill...","Approximately z = 10.0, corresponding to 13 bi...","Approximately z = 13.0, corresponding to 30 bi..."
2,3,Pick the best possible answer: What is the rea...,The sun appears yellowish due to a reflection ...,"The longer wavelengths of light, such as red a...",The sun appears yellowish due to the scatterin...,The sun emits a yellow light due to its own sp...,The atmosphere absorbs the shorter wavelengths...
3,4,What is the significance of the redshift-dista...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...
4,5,What is the Landau-Lifshitz-Gilbert equation u...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...

In [18]:
import torch

options = ["A", "B", "C", "D", "E"]

batch_size = 32

predictions = []

deberta_model.eval()
roberta_model.eval()

for start in range(0, len(test), batch_size):

    end = start + batch_size

    prompts = (
        test.iloc[start:end]["prompt"]
        .astype(str)
        .tolist()
    )

    # -------------------------
    # DeBERTa
    # -------------------------

    deberta_inputs = deberta_tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    deberta_inputs = {
        key: value.to(device)
        for key, value in deberta_inputs.items()
    }

    # -------------------------
    # RoBERTa
    # -------------------------

    roberta_inputs = roberta_tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    roberta_inputs = {
        key: value.to(device)
        for key, value in roberta_inputs.items()
    }

    # -------------------------
    # Inference
    # -------------------------

    with torch.no_grad():

        deberta_logits = deberta_model(
            **deberta_inputs
        ).logits

        roberta_logits = roberta_model(
            **roberta_inputs
        ).logits

    # -------------------------
    # Softmax
    # -------------------------

    deberta_probs = torch.softmax(
        deberta_logits,
        dim=-1
    )

    roberta_probs = torch.softmax(
        roberta_logits,
        dim=-1
    )

    # -------------------------
    # Weighted ensemble
    # -------------------------

    final_probs = (
        0.70 * deberta_probs
        + 0.30 * roberta_probs
    )

    # -------------------------
    # Top 3
    # -------------------------

    top3_indices = torch.argsort(
        final_probs,
        dim=-1,
        descending=True
    )[:, :3]

    for indices in top3_indices:

        prediction = " ".join(
            options[i.item()]
            for i in indices
        )

        predictions.append(prediction)

print("Total predictions:", len(predictions))

Total predictions: 500

In [19]:
submission = pd.DataFrame({
    "id": test["id"],
    "prediction": predictions
})

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

   id prediction
0   1      D B C
1   2      B D C
2   3      B C D
3   4      B D C
4   5      B D E

In [20]:
saved_submission = pd.read_csv(
    "submission.csv"
)

prediction_rows = len(saved_submission)

print("Prediction rows:", prediction_rows)

Prediction rows: 500

In [21]:
import torch

instruction = (
    "Answer the following multiple-choice question carefully:"
)

test_50 = test.iloc[:50].copy()

original_prompts = (
    test_50["prompt"]
    .astype(str)
    .tolist()
)

augmented_prompts = [
    instruction + " " + prompt
    for prompt in original_prompts
]

In [22]:
original_inputs = deberta_tokenizer(
    original_prompts,
    return_tensors="pt",
    padding=True,
    truncation=True
)

augmented_inputs = deberta_tokenizer(
    augmented_prompts,
    return_tensors="pt",
    padding=True,
    truncation=True
)

original_inputs = {
    key: value.to(device)
    for key, value in original_inputs.items()
}

augmented_inputs = {
    key: value.to(device)
    for key, value in augmented_inputs.items()
}

In [23]:
deberta_model.eval()

with torch.no_grad():

    original_logits = deberta_model(
        **original_inputs
    ).logits

    augmented_logits = deberta_model(
        **augmented_inputs
    ).logits

In [24]:
original_probs = torch.softmax(
    original_logits,
    dim=-1
)

augmented_probs = torch.softmax(
    augmented_logits,
    dim=-1
)

tta_probs = (
    original_probs + augmented_probs
) / 2

In [25]:
original_top1 = torch.argmax(
    original_probs,
    dim=-1
)

tta_top1 = torch.argmax(
    tta_probs,
    dim=-1
)

different_predictions = (
    original_top1 != tta_top1
).sum().item()

print("Original Top-1:")
print(original_top1)

print("\nTTA Top-1:")
print(tta_top1)

print(
    "\nDifferent Top-1 predictions:",
    different_predictions
)

Original Top-1:
tensor([3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        3, 1, 2, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
        2, 1], device='cuda:0')

TTA Top-1:
tensor([3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        3, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1], device='cuda:0')

Different Top-1 predictions: 8

In [26]:
import torch

test_100 = test.iloc[:100].copy()

prompts_100 = (
    test_100["prompt"]
    .astype(str)
    .tolist()
)

# -------------------------
# DeBERTa tokenization
# -------------------------

deberta_inputs_100 = deberta_tokenizer(
    prompts_100,
    return_tensors="pt",
    padding=True,
    truncation=True
)

deberta_inputs_100 = {
    key: value.to(device)
    for key, value in deberta_inputs_100.items()
}

# -------------------------
# RoBERTa tokenization
# -------------------------

roberta_inputs_100 = roberta_tokenizer(
    prompts_100,
    return_tensors="pt",
    padding=True,
    truncation=True
)

roberta_inputs_100 = {
    key: value.to(device)
    for key, value in roberta_inputs_100.items()
}

In [27]:
deberta_model.eval()
roberta_model.eval()

with torch.no_grad():

    deberta_logits_100 = deberta_model(
        **deberta_inputs_100
    ).logits

    roberta_logits_100 = roberta_model(
        **roberta_inputs_100
    ).logits

In [28]:
deberta_probs_100 = torch.softmax(
    deberta_logits_100,
    dim=-1
)

roberta_probs_100 = torch.softmax(
    roberta_logits_100,
    dim=-1
)

In [29]:
weighted_probs_100 = (
    0.70 * deberta_probs_100
    + 0.30 * roberta_probs_100
)

In [30]:
deberta_top1 = torch.argmax(
    deberta_probs_100,
    dim=-1
)

ensemble_top1 = torch.argmax(
    weighted_probs_100,
    dim=-1
)

different_count = (
    deberta_top1 != ensemble_top1
).sum().item()

print("DeBERTa Top-1:")
print(deberta_top1)

print("\nEnsemble Top-1:")
print(ensemble_top1)

print(
    "\nDifferent Top-1 predictions:",
    different_count
)

DeBERTa Top-1:
tensor([3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        3, 1, 2, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
        2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 2, 2, 1, 1, 1,
        1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 3, 3], device='cuda:0')

Ensemble Top-1:
tensor([3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        3, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1,
        2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 3, 3], device='cuda:0')

Different Top-1 predictions: 9

In [31]:
# Highest class probability for each row

deberta_confidence = torch.max(
    deberta_probs_100,
    dim=-1
).values

ensemble_confidence = torch.max(
    weighted_probs_100,
    dim=-1
).values

# Confidence Gain
confidence_gain = (
    ensemble_confidence - deberta_confidence
)

# Count strictly positive gains
positive_gain_count = (
    confidence_gain > 0
).sum().item()

print("DeBERTa confidence:")
print(deberta_confidence)

print("\nEnsemble confidence:")
print(ensemble_confidence)

print("\nConfidence gain:")
print(confidence_gain)

print(
    "\nRows with positive confidence gain:",
    positive_gain_count
)

DeBERTa confidence:
tensor([0.2615, 0.2588, 0.2664, 0.2795, 0.2888, 0.2539, 0.2563, 0.2483, 0.2747,
        0.2379, 0.3289, 0.2751, 0.2433, 0.3035, 0.2766, 0.2734, 0.2708, 0.2734,
        0.2678, 0.2820, 0.2473, 0.2581, 0.3347, 0.2500, 0.2749, 0.2581, 0.2944,
        0.2859, 0.2429, 0.2546, 0.2527, 0.2629, 0.2847, 0.2683, 0.2371, 0.2922,
        0.2871, 0.2698, 0.2549, 0.2852, 0.2710, 0.2693, 0.2463, 0.2695, 0.3098,
        0.2847, 0.2245, 0.2678, 0.2896, 0.2849, 0.3008, 0.2603, 0.2595, 0.2515,
        0.2773, 0.2751, 0.2527, 0.2832, 0.2693, 0.2495, 0.2610, 0.2900, 0.2413,
        0.2654, 0.2881, 0.2595, 0.2671, 0.2441, 0.2808, 0.2500, 0.2732, 0.2493,
        0.2494, 0.2581, 0.2739, 0.2610, 0.2708, 0.2786, 0.2585, 0.2417, 0.3223,
        0.2854, 0.2446, 0.2905, 0.2666, 0.3218, 0.3052, 0.2615, 0.2698, 0.2747,
        0.2744, 0.2463, 0.2783, 0.2751, 0.2659, 0.2595, 0.2759, 0.2649, 0.2605,
        0.2573], device='cuda:0', dtype=torch.float16)

Ensemble confidence:
tensor([0.2434, 0.2416, 0.2443, 0.2637, 0.2701, 0.2459, 0.2471, 0.2421, 0.2604,
        0.2352, 0.2983, 0.2608, 0.2391, 0.2806, 0.2618, 0.2600, 0.2577, 0.2597,
        0.2569, 0.2657, 0.2420, 0.2495, 0.2889, 0.2415, 0.2526, 0.2494, 0.2605,
        0.2606, 0.2333, 0.2469, 0.2456, 0.2528, 0.2676, 0.2564, 0.2339, 0.2731,
        0.2698, 0.2570, 0.2330, 0.2677, 0.2441, 0.2564, 0.2411, 0.2563, 0.2852,
        0.2679, 0.2205, 0.2554, 0.2577, 0.2675, 0.2790, 0.2506, 0.2422, 0.2437,
        0.2621, 0.2609, 0.2454, 0.2663, 0.2571, 0.2430, 0.2513, 0.2576, 0.2310,
        0.2543, 0.2698, 0.2501, 0.2553, 0.2336, 0.2621, 0.2432, 0.2600, 0.2439,
        0.2432, 0.2435, 0.2603, 0.2514, 0.2584, 0.2636, 0.2499, 0.2374, 0.2937,
        0.2680, 0.2402, 0.2716, 0.2554, 0.2930, 0.2820, 0.2515, 0.2579, 0.2616,
        0.2613, 0.2411, 0.2635, 0.2608, 0.2544, 0.2507, 0.2615, 0.2532, 0.2429,
        0.2411], device='cuda:0')

Confidence gain:
tensor([-0.0181, -0.0172, -0.0221, -0.0158, -0.0188, -0.0080, -0.0092, -0.0062,
        -0.0142, -0.0027, -0.0306, -0.0144, -0.0042, -0.0228, -0.0149, -0.0134,
        -0.0131, -0.0137, -0.0110, -0.0163, -0.0054, -0.0085, -0.0458, -0.0085,
        -0.0223, -0.0087, -0.0339, -0.0252, -0.0096, -0.0078, -0.0071, -0.0102,
        -0.0170, -0.0119, -0.0031, -0.0191, -0.0173, -0.0127, -0.0219, -0.0174,
        -0.0269, -0.0129, -0.0053, -0.0132, -0.0246, -0.0167, -0.0040, -0.0125,
        -0.0319, -0.0174, -0.0218, -0.0097, -0.0174, -0.0078, -0.0153, -0.0142,
        -0.0073, -0.0169, -0.0122, -0.0066, -0.0097, -0.0324, -0.0103, -0.0111,
        -0.0183, -0.0095, -0.0118, -0.0106, -0.0186, -0.0068, -0.0132, -0.0054,
        -0.0062, -0.0146, -0.0136, -0.0096, -0.0124, -0.0150, -0.0086, -0.0043,
        -0.0286, -0.0174, -0.0045, -0.0189, -0.0112, -0.0288, -0.0231, -0.0099,
        -0.0119, -0.0131, -0.0131, -0.0053, -0.0148, -0.0144, -0.0114, -0.0088,
        -0.0144, -0.0117, -0.0176, -0.0162], device='cuda:0')

Rows with positive confidence gain: 0

In [32]:
# Get ordered Top-3 class indices

deberta_top3 = torch.argsort(
    deberta_probs_100,
    dim=-1,
    descending=True
)[:, :3]

ensemble_top3 = torch.argsort(
    weighted_probs_100,
    dim=-1,
    descending=True
)[:, :3]

# Check whether ANY position changed in each row

top3_changed = (
    deberta_top3 != ensemble_top3
).any(dim=1)

# Count changed rows

top3_changed_count = (
    top3_changed.sum().item()
)

print(
    "Rows with changed ordered Top-3:",
    top3_changed_count
)

Rows with changed ordered Top-3: 22

In [33]:
options = ["A", "B", "C", "D", "E"]

deberta_top3_strings = [
    " ".join(options[i.item()] for i in row)
    for row in deberta_top3
]

ensemble_top3_strings = [
    " ".join(options[i.item()] for i in row)
    for row in ensemble_top3
]

for i in range(100):
    if deberta_top3_strings[i] != ensemble_top3_strings[i]:
        print(
            i,
            "DeBERTa:",
            deberta_top3_strings[i],
            "| Ensemble:",
            ensemble_top3_strings[i]
        )

1 DeBERTa: D B C | Ensemble: B D C
2 DeBERTa: C B D | Ensemble: B C D
4 DeBERTa: B D C | Ensemble: B D E
9 DeBERTa: B C D | Ensemble: B E D
20 DeBERTa: B C D | Ensemble: B D C
21 DeBERTa: B C D | Ensemble: B D C
23 DeBERTa: C B D | Ensemble: B C D
28 DeBERTa: E B D | Ensemble: B E D
31 DeBERTa: B D C | Ensemble: B D E
34 DeBERTa: B D C | Ensemble: B D E
43 DeBERTa: B C D | Ensemble: B D C
46 DeBERTa: C E B | Ensemble: B E C
51 DeBERTa: B D C | Ensemble: B D E
52 DeBERTa: D C B | Ensemble: D B C
53 DeBERTa: B C D | Ensemble: B D C
56 DeBERTa: B C D | Ensemble: B D C
62 DeBERTa: D B C | Ensemble: B D C
67 DeBERTa: C B E | Ensemble: B C E
68 DeBERTa: C B D | Ensemble: B C D
72 DeBERTa: B D C | Ensemble: B D E
73 DeBERTa: C B D | Ensemble: B C D
82 DeBERTa: B D C | Ensemble: B D E

In [34]:
print(len([
    i
    for i in range(100)
    if deberta_top3_strings[i] != ensemble_top3_strings[i]
]))

22

In [35]:
val_100 = train.iloc[:100].copy()

val_prompts = (
    val_100["prompt"]
    .astype(str)
    .tolist()
)

In [36]:
deberta_val_inputs = deberta_tokenizer(
    val_prompts,
    return_tensors="pt",
    padding=True,
    truncation=True
)

deberta_val_inputs = {
    key: value.to(device)
    for key, value in deberta_val_inputs.items()
}

roberta_val_inputs = roberta_tokenizer(
    val_prompts,
    return_tensors="pt",
    padding=True,
    truncation=True
)

roberta_val_inputs = {
    key: value.to(device)
    for key, value in roberta_val_inputs.items()
}

In [37]:
deberta_model.eval()
roberta_model.eval()

with torch.no_grad():

    deberta_val_logits = deberta_model(
        **deberta_val_inputs
    ).logits

    roberta_val_logits = roberta_model(
        **roberta_val_inputs
    ).logits

In [38]:
deberta_val_probs = torch.softmax(
    deberta_val_logits,
    dim=-1
)

roberta_val_probs = torch.softmax(
    roberta_val_logits,
    dim=-1
)

weighted_val_probs = (
    0.70 * deberta_val_probs
    + 0.30 * roberta_val_probs
)

In [39]:
top3_predictions = torch.argsort(
    weighted_val_probs,
    dim=-1,
    descending=True
)[:, :3]

In [40]:
true_labels = torch.tensor(
    val_100["label"].values,
    dtype=torch.long
)

In [41]:
map3_scores = []

for true_label, predictions in zip(
    true_labels,
    top3_predictions.cpu()
):

    predictions = predictions.tolist()
    true_label = true_label.item()

    if true_label == predictions[0]:
        score = 1.0

    elif true_label == predictions[1]:
        score = 1.0 / 2.0

    elif true_label == predictions[2]:
        score = 1.0 / 3.0

    else:
        score = 0.0

    map3_scores.append(score)

map3 = sum(map3_scores) / len(map3_scores)

print("MAP@3:", map3)
print("Rounded MAP@3:", round(map3, 4))

MAP@3: 0.435
Rounded MAP@3: 0.435