In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1/spm.model
/kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1/config.json
/kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1/tokenizer.json
/kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1/tokenizer_config.json
/kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1/model.safetensors
/kaggle/input/datasets/sharankumare/mcq-train/train.csv

In [2]:
import os
import transformers
import tokenizers
import numpy as np
import pandas as pd
import pickle
import gc
import os
import unicodedata

import torch
import transformers

import matplotlib.pyplot as plt

from tqdm.auto import tqdm

print("Transformers:", transformers.__version__)
print("Tokenizers:", tokenizers.__version__)

Transformers: 5.0.0
Tokenizers: 0.22.2

## Debert v3 large

In [3]:
train = pd.read_csv(
    "/kaggle/input/datasets/sharankumare/mcq-train/train.csv"
)

print("Shape:", train.shape)
print("Columns:", train.columns.tolist())

Shape: (2000, 8)
Columns: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer']

In [4]:
import re

def normalize_question(text):
    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^\w\s]", "", text)
    return text


train["question_key"] = train["prompt"].apply(normalize_question)

print("Before:", len(train))

train = (
    train
    .drop_duplicates(subset="question_key")
    .drop(columns="question_key")
    .reset_index(drop=True)
)

print("After:", len(train))

Before: 2000
After: 1758

In [5]:
label_map = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}

train["label"] = train["answer"].map(label_map)

train[["answer", "label"]].head(10)

  answer  label
0      B      1
1      A      0
2      C      2
3      B      1
4      A      0
5      C      2
6      E      4
7      A      0
8      A      0
9      A      0

## train/val

In [6]:
from sklearn.model_selection import train_test_split

train_df, valid_df = train_test_split(
    train,
    test_size=0.15,
    random_state=42,
    stratify=train["label"]
)

print("Train:", train_df.shape)
print("Validation:", valid_df.shape)

Train: (1494, 9)
Validation: (264, 9)

## Tokenizing

In [7]:
import os

os.environ["HF_TOKEN"] = "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"
os.environ["HF_HUB_DISABLE_XET"] = "1"
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "600"

print("HF token set:", bool(os.environ.get("HF_TOKEN")))

HF token set: True

In [8]:
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

from transformers import DebertaV2Tokenizer, DebertaV2ForMultipleChoice

MODEL_PATH = "/kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1"

tokenizer = DebertaV2Tokenizer.from_pretrained(MODEL_PATH)
print("Tokenizer loaded.")

model = DebertaV2ForMultipleChoice.from_pretrained(MODEL_PATH)
print(f"Model loaded. Params: {sum(p.numel() for p in model.parameters())/1e6:.1f}M")

Tokenizer loaded.

Loading weights:   0%|          | 0/390 [00:00<?, ?it/s]

DebertaV2ForMultipleChoice LOAD REPORT from: /kaggle/input/models/illuminatep/deberta-v3-plain/transformers/large/1
Key                 | Status  |
--------------------+---------+-
classifier.bias     | MISSING |
classifier.weight   | MISSING |
pooler.dense.bias   | MISSING |
pooler.dense.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded. Params: 435.1M

## MAP@3

In [9]:
def map_at_3(predictions, labels):
    map_sum = 0
    pred = np.argsort(-1*np.array(predictions),axis=1)[:,:3]
    for x,y in zip(pred,labels):
        z = [1/i if y==j else 0 for i,j in zip([1,2,3],x)]
        map_sum += np.sum(z)
    return map_sum / len(predictions)

def compute_metrics(p):
    predictions = p.predictions.tolist()
    labels = p.label_ids.tolist()
    return {"map@3": map_at_3(predictions, labels)}

## Train and save

In [10]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    warmup_steps=21,
    learning_rate=2e-5,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=2,
    num_train_epochs=2,
    report_to="none",
    output_dir="/kaggle/working/deberta-v3-large-mcq",
    fp16=True,
    gradient_accumulation_steps=8,
    logging_steps=25,
    eval_strategy="steps",
    eval_steps=25,
    save_strategy="steps",
    save_steps=25,
    load_best_model_at_end=False,
    metric_for_best_model="map@3",
    lr_scheduler_type="cosine",
    weight_decay=0.01,
    save_total_limit=2
)

In [11]:
import random
from torch.utils.data import Dataset


class MCQDataset(Dataset):

    def __init__(
        self,
        df,
        tokenizer,
        question_dropout=0.5
    ):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.question_dropout = question_dropout


    def __len__(self):
        return len(self.df)


    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        question = row["prompt"]

        if random.random() < self.question_dropout:
            question = ""

        options = [
            row["A"],
            row["B"],
            row["C"],
            row["D"],
            row["E"]
        ]

        encoded = self.tokenizer(
            [question] * 5,
            options,
            truncation=True,
            max_length=512,
            padding=False
        )

        encoded["label"] = int(row["label"])

        return encoded

In [12]:
from datasets import Dataset

train_dataset = MCQDataset(
    train_df,
    tokenizer,
    question_dropout=0.5
)

valid_dataset = MCQDataset(
    valid_df,
    tokenizer,
    question_dropout=0.0
)

print("Train:", len(train_dataset))
print("Valid:", len(valid_dataset))

Train: 1494
Valid: 264

In [13]:
# tokenized_dataset = train_dataset.map(
#     preprocess_function,
#     remove_columns=train_dataset.column_names
# )

# tokenized_dataset_valid = valid_dataset.map(
#     preprocess_function,
#     remove_columns=valid_dataset.column_names
# )

# print(tokenized_dataset)
# print(tokenized_dataset_valid)

In [14]:
from transformers import DataCollatorForMultipleChoice

data_collator = DataCollatorForMultipleChoice(
    tokenizer=tokenizer
)

print("Data collator ready")

Data collator ready

In [15]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.save_model(
    "/kaggle/working/model_v2"
)

tokenizer.save_pretrained(
    "/kaggle/working/model_v2"
)

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('/kaggle/working/model_v2/tokenizer_config.json',
 '/kaggle/working/model_v2/tokenizer.json')

In [16]:
!cd /kaggle/working && zip -r model_v2.zip model_v2

  adding: model_v2/ (stored 0%)
  adding: model_v2/model.safetensors (deflated 16%)
  adding: model_v2/config.json (deflated 55%)
  adding: model_v2/training_args.bin (deflated 53%)
  adding: model_v2/tokenizer_config.json (deflated 49%)
  adding: model_v2/tokenizer.json (deflated 79%)

In [17]:
!ls -lh /kaggle/working/model_v2.zip

-rw-r--r-- 1 root root 1.4G Jul 14 12:49 /kaggle/working/model_v2.zip

In [18]:
!ls -lh /kaggle/working

total 1.4G
drwxr-xr-x 4 root root 4.0K Jul 14 12:47 deberta-v3-large-mcq
drwxr-xr-x 2 root root 4.0K Jul 14 12:47 model_v2
-rw-r--r-- 1 root root 1.4G Jul 14 12:49 model_v2.zip